import React from 'react'
import Head from "next/head";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import theme from "../../src/theme/theme";
import FullLayout from "../../src/layouts/FullLayout";
import ProductPerfomance from "../../src/components/dashboard/ProductPerfomance";

const AllOrders = () => {
    return (
        <>
            <Head>
                <title>All Orders</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.png" />
            </Head>
            <ThemeProvider theme={theme}>
                <CssBaseline >
                    <FullLayout>
                        <ProductPerfomance title={"All Orders"} />
                    </FullLayout>
                </CssBaseline>
            </ThemeProvider>
        </>
    )
}

export default AllOrders
