import React from "react";
import Head from "next/head";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import theme from "../../src/theme/theme";
import FullLayout from "../../src/layouts/FullLayout";
import ProductPerfomance from "../../src/components/dashboard/ProductPerfomance";


const AllProducts = () => {

    return (
        <>
            <Head>
                <title>All Products</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.png" />
            </Head>
            <ThemeProvider theme={theme}>
                <CssBaseline >
                    <FullLayout>
                        <ProductPerfomance title={"All Products"} />
                    </FullLayout>
                </CssBaseline>
            </ThemeProvider>
        </>
    )
}

export default AllProducts