import React from 'react'
import PropTypes from "prop-types";
import Head from "next/head";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import { CacheProvider } from "@emotion/react";
import theme from "../../src/theme/theme";
import createEmotionCache from "../../src/createEmotionCache";
import FullLayout from "../../src/layouts/FullLayout";
import Images from '../../components/Images';

const clientSideEmotionCache = createEmotionCache();

const ImageUploader = (props) => {
    const { Component, emotionCache = clientSideEmotionCache, pageProps } = props;

    return (
        <CacheProvider value={emotionCache}>
            <Head>
                <title>Upload Image</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.png" />
            </Head>
            <ThemeProvider theme={theme}>
                <CssBaseline >
                    <FullLayout>
                        <Images/>
                    </FullLayout>
                </CssBaseline>
            </ThemeProvider>
        </CacheProvider>
    )
}

export default ImageUploader

ImageUploader.propTypes = {
    Component: PropTypes.elementType.isRequired,
    emotionCache: PropTypes.object,
    pageProps: PropTypes.object.isRequired,
};
