import Head from 'next/head'
import Image from 'next/image'
import Content from '../components/Content'

export default function Home() {
  return (
    <div>
      <Head>
        <title>E-Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='cover'>
        {/* <Image src={'/cover.jpg'} height={400} width={800}/> */}
        <img src="/cover.jpg" alt="Cover Pic" />
      </div>


      {/* Content */}

      <Content/>

    </div>
  )
}
